# Generated by Django 5.1 on 2024-11-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('N', 'None'), ('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='N', max_length=1)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
